import { COST_CENTER_IDS } from './constants.js';
import type { CreditsUsedItem, UsageItem } from './usage.js';

// Task 5.1: historical fuel for Phase 5 forecasting (spec §4.3 -- trailing-7
// weighted + cycle-to-date burn, weekday seasonality, P50/P90, nightly
// backtest/MAPE). ADDITIVE ONLY -- nothing here is read by any existing
// consumer unless it explicitly asks for it (see handlers.ts's usage/
// users-28-day handlers: a year/month[/day] or since/until query param must
// be present for these rows to be included in a response). Every current-
// cycle pin in usage.ts (189,800 burned, 193,036 totalQuantity, every persona
// MTD figure) is therefore untouched by this file's existence.
//
// Three closed monthly cycles precede the open June 2026 cycle (usage.ts):
// March, April, May 2026. Each is generated by a pure, deterministic formula
// (no Math.random(), no wall-clock) from a small "plan" of target totals --
// see fixtures/README.md's "Historical cycles" coherence note for the exact
// resulting figures and the ramp narrative (adoption trending up toward
// June's day-13 pace).

interface ClosedCyclePlan {
  year: number;
  month: number; // 1-12
  targetTotalCredits: number; // enterprise-wide, pool-covered, billing-view credits for the whole closed cycle
}

// Chosen to land in the 380k-470k "plausible, under the 567,000 pool" band
// (CLAUDE.md-brief Task 5.1) with a gentle upward ramp toward June's
// day-13-annualised pace (189,800 / 13 * 30 ≈ 437,800) -- consistent with the
// README's "realistic adoption curve" narrative, not a flat repeat.
const CLOSED_CYCLES: ClosedCyclePlan[] = [
  { year: 2026, month: 3, targetTotalCredits: 405_000 },
  { year: 2026, month: 4, targetTotalCredits: 429_000 },
  { year: 2026, month: 5, targetTotalCredits: 452_000 },
];

// Weekend burn as a fraction of a weekday's rate. 0.3 sits inside Task 5.1's
// requested 25-40% band and yields a weekday:weekend ratio of exactly
// 1/0.3 = 3.33x for every generated series (CC-level and per-persona alike)
// -- comfortably above the >2x a trailing-7 weekday-index computation needs
// to recover the seasonal signal, and easy to assert on directly.
const WEEKEND_RATIO = 0.3;

// Seat counts per cost center (constants.ts / README.md's org chart) -- used
// to split each closed cycle's enterprise total across the six CCs in the
// SAME proportion as the live seat roster. Deliberately seat-proportional
// (not skewed toward capBound/dataEval): the current cycle's cap-exhaustion
// crisis and amber-headroom warning are THIS cycle's story (README.md's
// "Narrative at day 13"), not a standing historical pattern -- so historical
// months read as "normal", making the current cycle's anomalies stand out
// rather than look like business as usual.
const CC_SEATS: Record<keyof typeof COST_CENTER_IDS, number> = {
  workforce: 24,
  employer: 16,
  capBound: 8,
  dataEval: 9,
  cyber: 11,
  corporate: 13,
};
const TOTAL_SEATS = 81;

function daysInMonth(year: number, month: number): number {
  return new Date(Date.UTC(year, month, 0)).getUTCDate();
}

function isWeekend(year: number, month: number, day: number): boolean {
  const dow = new Date(Date.UTC(year, month - 1, day)).getUTCDay();
  return dow === 0 || dow === 6;
}

function pad2(n: number): string {
  return String(n).padStart(2, '0');
}

function weekdayWeekendCounts(year: number, month: number): { weekdays: number; weekends: number } {
  const days = daysInMonth(year, month);
  let weekdays = 0;
  let weekends = 0;
  for (let day = 1; day <= days; day++) {
    if (isWeekend(year, month, day)) weekends++;
    else weekdays++;
  }
  return { weekdays, weekends };
}

// Pure, seeded generator (Task 5.1's requirement): every value is a
// deterministic function of CLOSED_CYCLES/CC_SEATS/WEEKEND_RATIO above, so
// re-running this module (or re-running the whole test suite) always
// produces byte-identical fixtures -- no randomness, no dependency on when
// the code happens to run.
function generateClosedCycleUsageItems(plan: ClosedCyclePlan): UsageItem[] {
  const days = daysInMonth(plan.year, plan.month);
  const { weekdays, weekends } = weekdayWeekendCounts(plan.year, plan.month);
  // Enterprise-wide credits for one weekday, s.t.
  // weekdays*weekdayUnit + weekends*(WEEKEND_RATIO*weekdayUnit) == target.
  const weekdayUnit = plan.targetTotalCredits / (weekdays + WEEKEND_RATIO * weekends);

  const items: UsageItem[] = [];
  for (const [key, seats] of Object.entries(CC_SEATS) as Array<[keyof typeof COST_CENTER_IDS, number]>) {
    const seatShare = seats / TOTAL_SEATS;
    for (let day = 1; day <= days; day++) {
      const weekend = isWeekend(plan.year, plan.month, day);
      const dayUnit = weekend ? weekdayUnit * WEEKEND_RATIO : weekdayUnit;
      const quantity = Math.round(dayUnit * seatShare);
      if (quantity <= 0) continue;
      const amountUsd = quantity / 100; // $0.01/credit; fully pool-covered historically -- no closed cycle ever exhausted its cap.
      items.push({
        date: `${plan.year}-${pad2(plan.month)}-${pad2(day)}`,
        product: 'copilot',
        sku: 'Copilot AI Credits',
        cost_center_id: COST_CENTER_IDS[key],
        user_login: null,
        quantity,
        gross_amount: amountUsd,
        discount_amount: amountUsd,
        net_amount: 0,
      });
    }
  }
  return items;
}

// Billing-view (CC-aggregate, `user_login: null`) rows for the three closed
// cycles above -- the enterprise/per-CC daily-burn fuel Task 5.1 (a)/(b)
// asks for. Only ever returned by the MSW usage handler when the request
// explicitly asks for a year/month outside the current cycle (handlers.ts);
// the default (no year param) response is exactly usage.ts's USAGE_ITEMS,
// unchanged.
export const HISTORICAL_USAGE_ITEMS: UsageItem[] = CLOSED_CYCLES.flatMap(generateClosedCycleUsageItems);

// -------- per-user historical rows (metrics view; Task 5.1 (c)) --------

interface PersonaPlan {
  userId: string;
  userLogin: string;
  // Baseline weekday credits/day this persona historically drew, before the
  // per-month ramp multiplier below. Named personas (emily-zhao, liam-obrien,
  // faisal-noor, hannah-webb) are anchored to their OWN current-cycle MTD
  // total / 13 (the day-13 daily rate usage.ts's CREDITS_USED_ITEMS already
  // pins) so the historical series reads as "the same person, earlier" rather
  // than an arbitrary number. noah-tanaka has 0 MTD this cycle (his only
  // June-cycle-adjacent rows are the Aug/Sep cliff fixture, both outside the
  // June window) so his historical rate is an independent, modest baseline --
  // narratively "active before, quiet this cycle, back for the cliff".
  dailyRateCredits: number;
}

// Ramp multiplier applied to each persona's baseline rate, by month -- same
// "trending up toward June" narrative as CLOSED_CYCLES' enterprise totals,
// applied per-user instead of per-CC.
const MONTH_RAMP: Record<number, number> = { 3: 0.7, 4: 0.82, 5: 0.93 };

// Anchors: 5480/13 (emily-zhao), 4930/13 (liam-obrien), 4180/13 (faisal-noor),
// 4360/13 (hannah-webb) -- each is that persona's own June CREDITS_USED_ITEMS
// rows (usage.ts) summed and divided by day-13-of-30's elapsed days, i.e.
// "this persona's current daily pace". faisal-noor's 4,180 and hannah-webb's
// 4,360 are both pinned figures elsewhere (Task 5.1 brief; README.md's
// "hannah-webb's 4,360" binding-max note) -- reusing them here (rather than
// picking fresh numbers) is what makes the historical series read as
// continuous with the persona, not a coincidence.
const PERSONA_PLANS: PersonaPlan[] = [
  { userId: '5182', userLogin: 'emily-zhao', dailyRateCredits: 5480 / 13 },
  { userId: '5107', userLogin: 'liam-obrien', dailyRateCredits: 4930 / 13 },
  { userId: '5044', userLogin: 'faisal-noor', dailyRateCredits: 4180 / 13 },
  { userId: '5921', userLogin: 'hannah-webb', dailyRateCredits: 4360 / 13 },
  { userId: '7219', userLogin: 'noah-tanaka', dailyRateCredits: 300 },
];

function generatePersonaMonthRows(plan: PersonaPlan, cycle: ClosedCyclePlan): CreditsUsedItem[] {
  const days = daysInMonth(cycle.year, cycle.month);
  const scale = MONTH_RAMP[cycle.month] ?? 1;
  const weekdayUnit = plan.dailyRateCredits * scale;

  const rows: CreditsUsedItem[] = [];
  for (let day = 1; day <= days; day++) {
    const weekend = isWeekend(cycle.year, cycle.month, day);
    const dayUnit = weekend ? weekdayUnit * WEEKEND_RATIO : weekdayUnit;
    const credits = Math.round(dayUnit);
    if (credits <= 0) continue;
    rows.push({
      date: `${cycle.year}-${pad2(cycle.month)}-${pad2(day)}`,
      user_id: plan.userId,
      user_login: plan.userLogin,
      ai_credits_used: credits,
      // model left unattributable (undefined) for historical rows: these
      // fall outside cycleBounds(SIM_CURRENT_DATE) so they never reach the
      // Users screen's model-mix bar (a current-cycle-only view) -- no
      // consumer needs a model tag on them yet.
    });
  }
  return rows;
}

// Metrics-view per-user rows for the named heavy-user personas across the
// three closed cycles. Only ever returned by the MSW users-28-day handler
// when the request carries `since`/`until` (handlers.ts); the default (no
// date params) response is exactly usage.ts's CREDITS_USED_ITEMS, unchanged.
export const HISTORICAL_CREDITS_USED_ITEMS: CreditsUsedItem[] = PERSONA_PLANS.flatMap((persona) =>
  CLOSED_CYCLES.flatMap((cycle) => generatePersonaMonthRows(persona, cycle)),
);
